### ISSUE TITLE
warning: remote HEAD refers to nonexistent ref, unable to checkout.

### ISSUE THREAD

**Issue by geekz** [bcoin-org/lcoin#3]
![lcoingitissue](https://user-images.githubusercontent.com/45522/27653157-d211b6e2-5c5b-11e7-811b-6a7e84662532.jpg)

When i git clone, i am getting this error. for Lcoin.

**Comment by checksum0** [comment]
When you clone a repo, the default branch is master but it doesn't exist on that repo. You can select the litecoin branch using `git clone http://github.com/bcoin-org/lcoin.git --branch litecoin` in the mean time before a master branch exists...

Also, if you only want to install lcoin, you don't need to clone the source, just `npm install -g lcoin --production` as long as you have already installed all dependencies.

**Comment by geekz** [comment]
Awesome. 
can you please help me with another issue?

````
murali@server:~/lcoin$ lcoin
[info] (chain) Chain is loading.
[info] (chain) Checkpoints are enabled.
[info] (chain) Coin cache is enabled.
[info] (chaindb) Opening ChainDB...
[error] (node) IO error: lock /home/murali/.lcoin/chain.ldb/LOCK: Resource temporarily unavailable
/home/murali/lcoin/lib/utils/co.js:345
    throw err;
    ^

Error: IO error: lock /home/murali/.lcoin/chain.ldb/LOCK: Resource temporarily u navailable
    at Error (native)
murali@server:~/lcoin$
```
`

**Comment by checksum0** [comment]
Look like your node can't attain an actual lock on the leveldb directory. I'd try to delete the database and ensure the lcoin has the necessary permission needed to write there and restart.

If it still happen starting from scratch with correct permission, I'd raise another issue specific to this.

**Comment by cronopio** [comment]
This issue was solved, should be closed now.

**Comment by checksum0** [comment]
Giving a work around in an issue comments is not a fix. 

There are still no master branch and instructions have no been updated to add the `--branch` switch. `git clone` per the readme instructions still fail here. Not fixed.

**Comment by checksum0** [comment]
Still fail here. Default branch still inexistant and instruction not updated to include `--branch` switch. Yes, it's only a warning but that git command clone an empty repo.

![lcoin](https://user-images.githubusercontent.com/26656348/31183901-f4c09bf4-a8f5-11e7-8980-a0a5328065e7.PNG)

**Comment by cronopio** [comment]
@checksum0 do you think adding `--branch litecoin` to the readme could solve the issue? I can submit a PR updating the readme.

**Comment by cronopio** [comment]
Submitted https://github.com/bcoin-org/lcoin/pull/9
